### PR TITLE
dev/handes trailing / in filepath 

### LINKED ISSUE #1386: FilePath with trailing / is not handled well
##### *Distribution: 

debian 12

##### *Detector type: 

Jungfrau, but should apply to all others as well

##### *Software Package Version: 

10.0.0

##### Priority:

Low

##### *Describe the bug

On many places in the code it is assumed, that the filePath has no trailing "/", but such a string is taken without complaints. This results in double slashes for example in the fname attribute of the ZMQ stream. As path names are often given with a trailing /, this is unfortunate.

##### Expected behavior

Double / should never appear in a path string. So a respective user input should be handled to avoid this.

##### To Reproduce

Call the API function setFilePath with a parameter like "/var/temp/test/" - anything with a trailing "/". Enable streaming, start an acquisition and have a look into the fname attribute of the ZMQ stream.

##### Additional context

I didn't dive deep enough into the code to be sure it's the right place to do this, but the following patch would resolve the issue:

slsDetectorPackage-10.0.0/slsReceiverSoftware/src/Implementation.cpp
489a490,491
>     while(filePath.back() == '/')
>         filePath.pop_back();

### PR DESCRIPTION
**Pull request by AliceMazzoleni99**
- filePath member in Receiver Implementation is of type std::filesystem::path

### CODE REVIEW

File: slsReceiverSoftware/src/Implementation.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@
 #include <cstdlib> //system
 #include <cstring>
 #include <cstring> //strcpy
+#include <filesystem>
```
Comment (thattil) [inline slsReceiverSoftware/src/Implementation.cpp]: Do you need this include here and in other places? This already includes "Implementation.h", which already includes the filesystem header.

File: slsReceiverSoftware/src/Implementation.cpp [hunk 2]
```diff
@@ -874,21 +879,24 @@ void Implementation::CreateUDPSockets() {
 void Implementation::SetupWriter() {
 
     try {
```
Comment (thattil) [inline slsReceiverSoftware/src/Implementation.cpp:878]: I think it is safer on all platforms if one still tries  to check if the path is empty.  If the user never sets it, it will be empty when it calls SetupWriter.

File: slsReceiverSoftware/src/Implementation.h [hunk 3]
```diff
@@ -316,7 +317,7 @@ class Implementation : private virtual slsDetectorDefs {
 
     // file parameters
     fileFormat fileFormatType{BINARY};
-    std::string filePath{};
+    std::filesystem::path filePath{};
```
Comment (thattil) [inline slsReceiverSoftware/src/Implementation.h:320]: filePath is used as a string to  many functions in Implementation.cpp. I doubt it is being converted to string everywhere. For eg. CreateMasterFile,  startACquiistionCallback, ResetParameters..

**Review by thattil — CHANGES_REQUESTED** [review]
Looks better using filesystem instad of string for file path! I think there are a few places its missed out in Implementation.cpp though.

File: slsReceiverSoftware/src/Implementation.cpp (hunk 1 above)
Comment (AliceMazzoleni99) [reply slsReceiverSoftware/src/Implementation.cpp]: removed all the unneccessary ones

File: slsReceiverSoftware/src/Implementation.cpp (hunk 2 above)
Comment (AliceMazzoleni99) [reply slsReceiverSoftware/src/Implementation.cpp:878]: Done.

File: slsReceiverSoftware/src/Implementation.h (hunk 3 above)
Comment (AliceMazzoleni99) [reply slsReceiverSoftware/src/Implementation.h:320]: Good point! Checked everywhere that filePath is used correctly.

File: slsReceiverSoftware/src/MasterFileUtility.cpp [hunk 4]
```diff
@@ -336,7 +337,15 @@ std::string CreateVirtualHDF5File(
                     os << filePath << "/" << fileNamePrefix << "_d"
```
Comment (thattil) [inline slsReceiverSoftware/src/MasterFileUtility.cpp]: this "os" variable is unused. I believe this is what you are replacing..

**Review by thattil — APPROVED** [review]
