### PR TITLE
1000/shm free obsolete

### LINKED ISSUE #1270: 10.0.0.rc : shared memory
$  p config moench03_20250210.config 
- 14:33:28.730 ERROR: Shared memory is invalid or freed. Close resources before access.
terminate called after throwing an instance of 'sls::SharedMemoryError'
  what():  Shared memory is invalid or freed. Close resources before access.
Aborted (core dumped)
[14:33:28][heymes_j@pc15676 Moench03]$  p free
- 14:34:15.318 ERROR: Shared memory is invalid or freed. Close resources before access.
terminate called after throwing an instance of 'sls::SharedMemoryError'
  what():  Shared memory is invalid or freed. Close resources before access.
Aborted (core dumped)
[14:34:15][heymes_j@pc15676 Moench03]$  which p
alias p='sls_detector_put'
	~/Software/ilgad/slsDetectorPackage/gui_build/bin/sls_detector_put
[14:34:30][heymes_j@pc15676 Moench03]$  ll /dev/shm/slsDetectorPackage_detector_0_ctbdacs*
-rw------- 1 heymes_j unx-nogroup 2540 Aug 14 10:40 /dev/shm/slsDetectorPackage_detector_0_ctbdacs

\

p config with old ctb shm..

$  p free
- 14:45:39.701 INFO: Shared memory deleted /slsDetectorPackage_detector_0
- 14:45:39.701 INFO: Shared memory deleted /slsDetectorPackage_detector_0_module_0
- 14:45:39.701 ERROR: Shared memory is invalid or freed. Close resources before access.
terminate called after throwing an instance of 'sls::SharedMemoryError'
  what():  Shared memory is invalid or freed. Close resources before access.
Aborted (core dumped)

an old shared memory existed with the ctb shm... so free only frees the multi and the module shm.. not the ctb one for some reason..

### PR DESCRIPTION
**Pull request by thattil**
#1275
#1278

### CODE REVIEW

File: slsDetectorSoftware/tests/test-CtbConfig.cpp [hunk 1]
```diff
@@ -10,7 +10,7 @@
 namespace sls {
 
 TEST_CASE("Default construction") {
-    static_assert(sizeof(CtbConfig) == ((18 + 32 + 64 + 5 + 8) * 20 + 1),
+    static_assert(sizeof(CtbConfig) == (4 + 4 + (18 + 32 + 64 + 5 + 8) * 20),
                   "Size of CtbConfig does not match");
```
Comment (AliceMazzoleni99) [inline slsDetectorSoftware/tests/test-CtbConfig.cpp]: why 4+4?

Comment (thattil) [reply slsDetectorSoftware/tests/test-CtbConfig.cpp]: 4 from int (shmversion), 4 (1 from bool (isValid) + 3 (padding)

File: slsDetectorSoftware/tests/test-CtbConfig.cpp [hunk 2]
```diff
@@ -10,7 +10,7 @@
...
```
Comment (AliceMazzoleni99) [inline slsDetectorSoftware/tests/test-CtbConfig.cpp:17]: why is it 4 + 4

Comment (AliceMazzoleni99) [reply slsDetectorSoftware/tests/test-CtbConfig.cpp:17]: Maybe use sizeof(int) to make it platform independant.

Comment (AliceMazzoleni99) [reply slsDetectorSoftware/tests/test-CtbConfig.cpp:17]: Maybe we can have int32_t it should be enough for the version.

**Review by AliceMazzoleni99 — COMMENTED** [review]
For me it looks Ok.
